### PR TITLE
updated question and result models

### PR DESCRIPTION
**Pull request by infrasonic26**

### CODE REVIEW

**Comment by zannujulius** [comment]
Good work

**Review by zannujulius — DISMISSED** [review]
this is good

**Review by paulobike — DISMISSED** [review]
Looks good

**Review by paulobike — DISMISSED** [review]
nice

**Review by zannujulius — DISMISSED** [review]
this is perfect

**Review by chukwunemejohnpaul — DISMISSED** [review]
ok

**Review by zannujulius — DISMISSED** [review]
good one

**Review by chukwunemejohnpaul — DISMISSED** [review]
okay

**Review by zannujulius — APPROVED** [review]
Perfect

**Review by paulobike — APPROVED** [review]
Looks good

**Review by chukwunemejohnpaul — APPROVED** [review]
ok

**Review by paulobike — APPROVED** [review]
Looks good

**Pull request merged**
